### ISSUE TITLE
Hyperpwn-client.sh do not work

### ISSUE THREAD

**Issue by null-null-programming** [bet4it/build-an-efficient-pwn-environment#5]
`from pwn import *

context.binary = './combo-chain'
context.log_level = 'debug'
context.terminal=['~/hyperpwn/hyperpwn-client.sh']

conn = gdb.debug('./combo-chain')`

Result:
` Starting local process '/usr/bin/gdbserver' argv=[b'/usr/bin/gdbserver', b'--multi', b'--no-disable-randomization', b'localhost:0', b'./combo-chain'] : pid 21153
[DEBUG] Received 0x43 bytes:
    b'Process ./combo-chain created; pid = 21157\n'
    b'Listening on port 45131\n'
[DEBUG] Wrote gdb script to '/tmp/pwn24bii4nz.gdb'
    target remote 127.0.0.1:45131
[*] running in new terminal: /usr/bin/gdb -q  "./combo-chain" -x /tmp/pwn24bii4nz.gdb
[DEBUG] Launching a new terminal: ['~/hyperpwn/hyperpwn-client.sh', '/usr/bin/gdb -q  "./combo-chain" -x /tmp/pwn24bii4nz.gdb']`

I set context.terminal , but the terminal where hyperpwn-server.sh work show nothing.
Help me ...

**Comment by bet4it** [comment]
When you run `echo 'pwd' > /tmp/hyperpwn-pipe`, are there any changes of the terminal of `hyperpwn-server.sh` ?
